let modalidades = [
  {
    tiluto: "Ritbox",
    professor: "Marquinhos",
    ndeaulas: 0,
    dias: ["Segunda-Feira", "Quarta-Feira"],
    horario: "18:00h às 19:00h",
    alunos: [
      {
        id: 1,
        nome: "ALCIONE DE AQUINO DE SOUZA",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 2,
        nome: "BEATRIZ CAVALCANTE DOS SANTOS",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 3,
        nome: "EUGÊNIA DE OLIVEIRA SANTOS",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 4,
        nome: "DELMA FERREIRA DOS SANTOS",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 5,
        nome: "ELIZABETH MARIA ALVES DE MELO SILVA",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 6,
        nome: "EDNA OLIVEIRA PONTES",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 7,
        nome: "EDJANE DA SILVA GOMES",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 8,
        nome: "DIAMAR REJANE DA CONCEIÇÃO",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
    ],
  },
  {
    tiluto: "ZUMBA",
    professor: "Ivison",
    ndeaulas: 0,
    dias: ["Terça-Feira", "Quinta-Feira"],
    horario: "17:00h às 18:00h",
    alunos: [
      {
        id: 1,
        nome: "DIAMAR REJANE DA CONCEIÇÃO",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 2,
        nome: "FRANCIMARY MORAIS DA SILVA COSTA",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 3,
        nome: "EUGÊNIA DE OLIVEIRA SANTOS",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 4,
        nome: "EMILLY PONTES DE SANTANA",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 5,
        nome: "ELIZABETH MARIA ALVES DE MELO SILVA",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 6,
        nome: "ELISANGELA SILVA DE ARAUJO LIMA",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 7,
        nome: "ELIANE DE LIMA NASCIMENTO",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 8,
        nome: "EDNA DA SILVA XAVIER",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
    ],
  },
  {
    tiluto: "Jiu-jitsu Manhã",
    professor: "Beto",
    ndeaulas: 0,
    dias: ["Terça-Feira", "Quinta-Feira"],
    horario: "09:00h às 11:00h",
    alunos: [
      {
        id: 1,
        nome: "DOUGLAS SANTOS PEREIRA",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 2,
        nome: "FRANCIMARY MORAIS DA SILVA COSTA",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 3,
        nome: "EUGÊNIA DE OLIVEIRA SANTOS",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 4,
        nome: "EMILLY PONTES DE SANTANA",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 5,
        nome: "ELIZABETH MARIA ALVES DE MELO SILVA",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 6,
        nome: "ELISANGELA SILVA DE ARAUJO LIMA",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
      {
        id: 7,
        nome: "ELIANE DE LIMA NASCIMENTO",
        presenca: 0,
        falta: 0,
        justificativa: 0,
      },
    ],
  },
];
